import { Event } from '../simulation/types/event.type';
import { Scenario } from '../simulation/types/scenario-config.type';

const defaultEvent: Event = {
  id: 'event-global-hype-wave',
  name: '\u0413\u043B\u043E\u0431\u0430\u043B\u044C\u043D\u0430\u044F \u0432\u043E\u043B\u043D\u0430 \u0445\u0430\u0439\u043F\u0430',
  type: 'trend',
  x: 0.85,
  y: 0.8,
  intensity: 0.8,
  severity: 0.7,
  relevance: 0.9,
  scope: 0.75,
  duration: 8,
  startStep: 2,
  isActive: true,
};

export const DEFAULT_SCENARIO: Scenario = {
  key: 'global-chaos-mvp',
  name: '\u0413\u043B\u043E\u0431\u0430\u043B\u044C\u043D\u044B\u0439 \u0445\u0430\u043E\u0441 MVP',
  states: [
    'calm',
    'interested',
    'reactive',
    'critical',
    'stabilized',
    'failed',
  ],
  successStates: ['stabilized'],
  failureStates: ['failed'],
  terminalStates: ['stabilized', 'failed'],
  riskMap: {
    calm: 0.1,
    interested: 0.3,
    reactive: 0.65,
    critical: 0.9,
    stabilized: 0.05,
    failed: 1,
  },
  transitionMatrix: {
    calm: {
      calm: 0.55,
      interested: 0.3,
      reactive: 0.1,
      critical: 0,
      stabilized: 0.05,
      failed: 0,
    },
    interested: {
      calm: 0.1,
      interested: 0.45,
      reactive: 0.3,
      critical: 0.1,
      stabilized: 0.05,
      failed: 0,
    },
    reactive: {
      calm: 0.05,
      interested: 0.15,
      reactive: 0.35,
      critical: 0.25,
      stabilized: 0.1,
      failed: 0.1,
    },
    critical: {
      calm: 0,
      interested: 0.05,
      reactive: 0.2,
      critical: 0.35,
      stabilized: 0.15,
      failed: 0.25,
    },
    stabilized: {
      stabilized: 1,
    },
    failed: {
      failed: 1,
    },
  },
  segmentPresets: {
    stable: {
      initialState: 'calm',
      temperature: { min: 0.1, max: 0.25 },
      weight: { min: 0.3, max: 0.55 },
      sensitivity: { min: 0.15, max: 0.35 },
      relevance: { min: 0.2, max: 0.5 },
      position: { min: 0.1, max: 0.45 },
    },
    regular: {
      initialState: 'interested',
      temperature: { min: 0.2, max: 0.45 },
      weight: { min: 0.35, max: 0.65 },
      sensitivity: { min: 0.3, max: 0.6 },
      relevance: { min: 0.35, max: 0.7 },
      position: { min: 0.25, max: 0.65 },
    },
    reactive: {
      initialState: 'reactive',
      temperature: { min: 0.35, max: 0.7 },
      weight: { min: 0.4, max: 0.8 },
      sensitivity: { min: 0.55, max: 0.9 },
      relevance: { min: 0.5, max: 0.95 },
      position: { min: 0.45, max: 0.85 },
    },
  },
  segmentDistribution: {
    stable: 0.35,
    regular: 0.45,
    reactive: 0.2,
  },
  events: [defaultEvent],
  clusterRadius: 0.18,
  hotTemperatureThreshold: 0.7,
  maxFailureDepth: 4,
  riskScoreWeights: {
    stateRisk: 0.3,
    temperature: 0.25,
    influence: 0.2,
    velocity: 0.1,
    failureProbability: 0.15,
  },
  chaosIndexWeights: {
    avgTemperature: 0.25,
    avgVelocity: 0.2,
    clusterDensity: 0.2,
    hotShare: 0.15,
    failureProximity: 0.2,
  },
  fixedThresholds: {
    local: 0.65,
    global: 0.7,
  },
  adaptiveThresholds: {
    localSigmaMultiplier: 0.5,
    globalSigmaMultiplier: 0.75,
    localMin: 0.35,
    localMax: 0.95,
    globalMin: 0.4,
    globalMax: 0.95,
  },
  defaultProfile: 'demo',
  profiles: {
    demo: {
      key: 'demo',
      label: 'Demo',
      hotThresholds: {
        system: 0.7,
        visual: 0.7,
      },
      eventLifecycle: {
        enabled: false,
        rampUpShare: 0.2,
        peakShare: 0.2,
        decayShare: 0.6,
        aftershockSteps: 0,
        aftershockIntensityMultiplier: 0,
        aftershockScopeMultiplier: 0,
        aftershockRelevanceMultiplier: 0,
      },
      delayedEffects: {
        localImmediateShare: 1,
        localNextStepShare: 0,
        systemImmediateShare: 1,
        systemNextStepShare: 0,
        decayFactor: 1,
      },
      inertia: {
        stressMemoryDecay: 1,
        temperatureRecovery: 1,
        influenceRecovery: 1,
        cooldownSteps: 0,
      },
      segmentDynamics: {
        stable: {
          sensitivityMultiplier: 1,
          recoveryFactor: 1.05,
          escalationBias: -0.02,
          transitionBias: 0.95,
        },
        regular: {
          sensitivityMultiplier: 1,
          recoveryFactor: 1,
          escalationBias: 0,
          transitionBias: 1,
        },
        reactive: {
          sensitivityMultiplier: 1.05,
          recoveryFactor: 0.95,
          escalationBias: 0.03,
          transitionBias: 1.05,
        },
      },
      noise: {
        influence: 0,
        temperature: 0,
        transition: 0,
      },
      stabilizedTerminal: true,
    },
    realistic: {
      key: 'realistic',
      label: 'Realistic',
      hotThresholds: {
        system: 0.7,
        visual: 0.62,
      },
      eventLifecycle: {
        enabled: true,
        rampUpShare: 0.25,
        peakShare: 0.25,
        decayShare: 0.5,
        aftershockSteps: 2,
        aftershockIntensityMultiplier: 0.35,
        aftershockScopeMultiplier: 0.55,
        aftershockRelevanceMultiplier: 0.65,
      },
      delayedEffects: {
        localImmediateShare: 0.65,
        localNextStepShare: 0.35,
        systemImmediateShare: 0.5,
        systemNextStepShare: 0.5,
        decayFactor: 0.6,
      },
      inertia: {
        stressMemoryDecay: 0.78,
        temperatureRecovery: 0.08,
        influenceRecovery: 0.06,
        cooldownSteps: 2,
      },
      segmentDynamics: {
        stable: {
          sensitivityMultiplier: 0.8,
          recoveryFactor: 1.2,
          escalationBias: -0.12,
          transitionBias: 0.88,
        },
        regular: {
          sensitivityMultiplier: 1,
          recoveryFactor: 1,
          escalationBias: 0,
          transitionBias: 1,
        },
        reactive: {
          sensitivityMultiplier: 1.18,
          recoveryFactor: 0.82,
          escalationBias: 0.16,
          transitionBias: 1.12,
        },
      },
      noise: {
        influence: 0.025,
        temperature: 0.02,
        transition: 0.015,
      },
      stabilizedTerminal: true,
    },
  },
};

export const SCENARIOS: Scenario[] = [DEFAULT_SCENARIO];
